export const POST_ARTICLE_LOADING = "POST_ARTICLE_LOADING"
export const POST_ARTICLE_SUCCESS = "POST_ARTICLE_SUCCESS"
export const POST_ARTICLE_FAILED = "POST_ARTICLE_FAILED"



export const GET_ARTICLE_LOADING = "GET_ARTICLE_LOADING"
export const GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS"
export const GET_ARTICLE_FAILED = "GET_ARTICLE_FAILED"


