
export const GET_PUBLIC_USER_INFO_LOADING = "GET_PUBLIC_USER_INFO_LOADING"
export const GET_PUBLIC_USER_INFO_FAILED = "GET_PUBLIC_USER_INFO_FAILED"
export const GET_PUBLIC_USER_INFO_SUCCESS = "GET_PUBLIC_USER_INFO_SUCCESS"

