


export const GET_PROFILE_LOADING = "GET_PROFILE_LOADING"
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED"
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS"

export const UPDATE_PROFILE_LOADING = "UPDATE_PROFILE_LOADING"
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"

export const UPLOAD_AVATAR_LOADING = "UPLOAD_AVATAR_LOADING"
export const UPLOAD_AVATAR_FAILED = "UPLOAD_AVATAR_FAILED"
export const UPLOAD_AVATAR_SUCCESS = "UPLOAD_AVATAR_SUCCESS"
export const UPLOAD_AVATAR_PROGRESS = "UPLOAD_AVATAR_PROGRESS"


export const UPDATE_PASSWORD_LOADING = "UPDATE_PASSWORD_LOADING"
export const UPDATE_PASSWORD_FAILED = "UPDATE_PASSWORD_FAILED"
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS"


export const GET_TOTUR_INFO_LOADING = "GET_TOTUR_INFO_LOADING"
export const GET_TOTUR_INFO_FAILED = "GET_TOTUR_INFO_FAILED"
export const GET_TOTUR_INFO_SUCCESS = "GET_TOTUR_INFO_SUCCESS"


export const UPDATE_TOTUR_INFO_LOADING = "UPDATE_TOTUR_INFO_LOADING"
export const UPDATE_TOTUR_INFO_FAILED = "UPDATE_TOTUR_INFO_FAILED"
export const UPDATE_TOTUR_INFO_SUCCESS = "UPDATE_TOTUR_INFO_SUCCESS"


